# Receive repository dispatch and do something

name: Repository Dispatch
on:
  repository_dispatch:
    types: new-note
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
