# Receive repository dispatch and publish to gh-pages branch using cached dependencies and Gatsby Incremental Builds

name: Publish on Repository Dispatch

on:
  repository_dispatch:
    types: new-note

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Gatsby Cache Folder
      uses: actions/cache@v2
      id: gatsby-cache-folder
      with:
        path: .cache
        key: ${{ runner.os }}-cache-gatsby
        restore-keys: |
          ${{ runner.os }}-cache-gatsby

    - name: Gatsby Public Folder
      uses: actions/cache@v2
      id: gatsby-public-folder
      with:
        path: public/
        key: ${{ runner.os }}-public-gatsby
        restore-keys: |
          ${{ runner.os }}-public-gatsby

    - name: Install dependencies
      run: yarn install

    - name: Build Gatsby page
      run: yarn build --prefix-paths --log-pages
      env:
        GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
        CI: true

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./public
